services:
  fortune:
    # 容器名
    container_name: fortuneboot
    # 使用镜像
    image: 'registry.cn-hangzhou.aliyuncs.com/chishenjianglin/fortuneboot:all-in-one'
    # 环境变量
    environment:
      # 数据库连接池账号密码，建议修改
      - DRUID_USERNAME=${DRUID_USERNAME:-fortuneboot}
      - DRUID_PASSWORD=${DRUID_PASSWORD:-123456}
      # swagger文档开关，建议关闭，若要开启，把false改为true
      - SWAGGER_ENABLE=${SWAGGER_ENABLE:-false}
      # 时区，指定亚洲上海，如果是其他国家使用，改为对应国家的时区。
      - TZ=${TZ:-Asia/Shanghai}
      # 数据库密码，建议修改
      # 注: MYSQL_ROOT_PASSWORD和DB_PASSWORD的值必须一样
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-Jk9Lm2XqPvZt8N7e}
      - DB_PASSWORD=${DB_PASSWORD:-Jk9Lm2XqPvZt8N7e}
      # 建议替换RSA公私钥，密钥对生成 http://web.chacuo.net/netrsakeypair
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujkO6pmYnXtrCOJitQEpziHsbBgLwB3ixbEQuTXSo7dMX9y+jbzDQt/f3iRqU/2GDAZ1dFpC9YMyV3Td4kdYlwaOcJu1tyFC7AfEuaDJmfrlwzs8ykDC1QlyJiu2unyIwlSida3dcjHWCAUoN/KubSL6vRLY/0amuCzl4Wys7bncqeCBEJClsEPNTX57glhY1nIGei+1SncKMHgxIudeNnP5wV1zqAENfGWMbsVGaG3YQ4d3o/9nh2k5k0YtwWZ4HPfty1BhovCZ3yVW0VcM6le/9lHPjjuOeEDXsgGMrBP4CzFH4VAwDtOYPPtdsIVsc3QIP5BsfA029dkUFPJjIQIDAQAB}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY:-MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6OQ7qmZide2sI4mK1ASnOIexsGAvAHeLFsRC5NdKjt0xf3L6NvMNC39/eJGpT/YYMBnV0WkL1gzJXdN3iR1iXBo5wm7W3IULsB8S5oMmZ+uXDOzzKQMLVCXImK7a6fIjCVKJ1rd1yMdYIBSg38q5tIvq9Etj/Rqa4LOXhbKztudyp4IEQkKWwQ81NfnuCWFjWcgZ6L7VKdwoweDEi5142c/nBXXOoAQ18ZYxuxUZobdhDh3ej/2eHaTmTRi3BZngc9+3LUGGi8JnfJVbRVwzqV7/2Uc+OO454QNeyAYysE/gLMUfhUDAO05g8+12whWxzdAg/kGx8DTb12RQU8mMhAgMBAAECggEACrG0bk1i7UclSkbkxtCJ2+px87vBxrTC8dVo2uDcibPA6A/WM0r5FDjJoRt4QEdivkydzCKcjhGxI/l0R2sPeOllDGR0xJg40zMp3WjZ+LJ5JV7lXPLn/WjRmg2QUT0EvPeh2wvpvGE7/zGgDTebjP980nKMf1a3MbsFw2mW/Uhmm+ij4Hcpzi0h8/K6J0GdXTMIWRXdW2VjyPaIGtOje3tKwzUuu2AVFY2FF1IpfoRydAQZppLogeofeAGxGJzNagqZhV1lpYQQwTnFZzRuBHsIHAW4VAWeuSXqLgf3+/MhnDYuVJFqjnYXRe529SJarN5yo5vXoXfSFJedr+tDLQKBgQD2jc4XaTkygUwfSNyaZiNS7kBLEUcnryBPkIxhPfsO0a6Cd6nB2HeQgPfkgm24+614TPpZqGN0tBWGVR5F4kToFycEFPjegEBGRSaHXtktE3ZrfjuQxjnlgpyHJoSmHslJL3evIOpnTUpHG+ybVJ0oKAjlcFiV7NBwnlsP8Yi9SwKBgQDBW4cfDqIC2UuH0HGJ/JzgmIjjLKC2fSKuVmsD+TrmwCDl52CO5c1XZr43aKCb+8r395UeHKYHi4DFjQn9OpE4pX0GXGyggcCflH+eKcUMLOdBlbntY1R3zmO2M0jLvOrrsaJuz0g8Q1zoajeKSfA6eYmpfHZ1gJeN9qvQVp25wwKBgQCBi+Lk1Cn0ipF3wq3/Bnm7AmqPxuVPSao9hCLumUWH9M6vyLZOnzG7oLgfvhRu5Paxxiio4VxYnqLMsX61k31HQZsDfw2Aw3yCL6Vd7Y1JLPfE5U/g8vbKzAT40llSe8yhgqptP2tKmgbUNCzvNNdamSaLf6tcI1EmS15nky6Y3wKBgCzv15xZKz/cPliHEgwOoGr2KEIbuhIPTQMVZHOc9ZpxJnQn7OHo+GsKnsSD1WfLAeXVLVu9LrzsJ/ZBjAPFG8D9fOwAiOJYpWqw+WPJs1jcCrbMVFSeVCAv4C6VBqMK+dHjC6wTEmenBC2jmdrSyjjczCiOm309cHt2y4F0z90/AoGANyxVCvn5ZOIgkLF+eK6fngnu0kYZf2nxRyX5T0vdXFQLP0wDfDQOz/RNaMVeHCpJ7KnWGFT2xwd0WiUP9+cmVDUrmSfw89scf4JLdpkyvrKb2K/Rl7ekLbfgRbNWuyd2Ht1A/KQU3Ll7zSY/8WnT0eqKiBWftMmsWfylVx1IKkw=}
    volumes:
      # 存储卷位置/var/lib/docker/volumes/fortune_mysql_data/_data
      - 'mysql_data:/var/lib/mysql'
      - 'redis_data:/redis'
    ports:
      # 以下端口分别是: http、数据库、redis、java后端
      - '46031:80'
      - '46032:3306'
      - '46033:6379'
      - '46034:8080'
    # 重启策略：总是重启
    restart: always
    tty: true
    stdin_open: true

volumes:
  mysql_data:
  redis_data:
